import 'package:flutter/material.dart';

class Product {
  final String title;
  final String description;
  final String image;
  final String review;
  final String seller;
  final double price;
  final List<Color> colors;
  final String category;
  final double rate;
  int quantity;

  Product({
    required this.title,
    required this.description,
    required this.image,
    required this.review,
    required this.seller,
    required this.price,
    required this.colors,
    required this.category,
    required this.rate,
    required this.quantity,
  });
}

final List<Product> products = [
  Product(
    title: "Adidas Men's Shoes",
    description:
        "Men's Casual sneaker shoes running shoes walking shoes Running Shoes For Men",
    image: "assets/images/shoes.jpg",
    review: "(320 Reviews)",
    seller: "Adidas",
    price: 190,
    colors: [
      Colors.black,
      Colors.grey,
      Colors.blue,
    ],
    category: "Casuals",
    rate: 5.0,
    quantity: 1,
  ),
  Product(
    title: "Laptop",
    description: "Macbook Air Apple M1 - (8 GB/SSD/256 GB SSD/Mac OS Big Sur)",
    image: "assets/images/laptop.jpg",
    review: "(5689 Reviews)",
    seller: "apple",
    price: 920,
    colors: [
      Colors.black,
      Colors.grey,
      Colors.blue,
    ],
    category: "Casuals",
    rate: 9.7,
    quantity: 1,
  ),
  Product(
    title: "Rolex Watch",
    description: "WH Day and Date Analog Watch - For Men",
    image: "assets/images/watch.jpg",
    review: "(520 Reviews)",
    seller: "Rolex",
    price: 370,
    colors: [
      Colors.black,
      Colors.grey,
      Colors.blue,
    ],
    category: "Casuals",
    rate: 5.2,
    quantity: 1,
  ),
  Product(
    title: "Phone",
    description: "iphone 14 (blue,128 GB)",
    image: "assets/images/mobile.jpg",
    review: "(320 Reviews)",
    seller: "apple",
    price: 690,
    colors: [
      Colors.black,
      Colors.blue,
      Colors.grey,
    ],
    category: "Casuals",
    rate: 9.2,
    quantity: 1,
  ),
  Product(
    title: "Idee",
    description: "UV Protection Retro Square Sunglasses",
    image: "assets/images/sunglasses.jpg",
    review: "(320 Reviews)",
    seller: "Idee",
    price: 90,
    colors: [
      Colors.blue,
      Colors.black,
      Colors.grey,
    ],
    category: "Casuals",
    rate: 4.2,
    quantity: 1,
  ),
  Product(
    title: "Adidas Women's Shoes",
    description:
        "Women's Casual sneaker shoes running shoes walking shoes Running Shoes For Women",
    image: "assets/images/shoes4.jpg",
    review: "(320 Reviews)",
    seller: "Adidas",
    price: 150,
    colors: [
      Colors.black,
      Colors.pinkAccent.shade100,
      Colors.grey,
    ],
    category: "Casuals",
    rate: 4.2,
    quantity: 1,
  ),
  Product(
    title: "Arrow men's Fashion",
    description: "Men Slim Fit Seif Design Spread Collar Casual Shirt",
    image: "assets/images/shirt.jpg",
    review: "(320 Reviews)",
    seller: "Adidas",
    price: 190,
    colors: [
      Colors.black,
      Colors.cyanAccent.shade400,
      Colors.grey,
    ],
    category: "Casuals",
    rate: 6.2,
    quantity: 1,
  ),
  Product(
    title: "Athena Women's Fashion",
    description: "Women Printed Cotton Rayon Anarkali Kurta",
    image: "assets/images/fashion.jpg",
    review: "(320 Reviews)",
    seller: "Adidas",
    price: 150,
    colors: [
      Colors.black,
      Colors.pinkAccent.shade100,
      Colors.grey,
    ],
    category: "Casuals",
    rate: 5.2,
    quantity: 1,
  ),
];
final List<Product> mensshoes = [
  Product(
    title: "Adidas Men's Shoes",
    description:
        "Men's Casual sneaker shoes running shoes walking shoes Running Shoes For Men",
    image: "assets/images/shoes.jpg",
    review: "(320 Reviews)",
    seller: "Adidas",
    price: 200,
    colors: [
      Colors.black,
      Colors.grey,
      Colors.blue,
    ],
    category: "Casuals",
    rate: 5.2,
    quantity: 1,
  ),
  Product(
    title: "Adidas Men's Shoes",
    description:
        "Men's Casual sneaker shoes running shoes walking shoes Running Shoes For Men",
    image: "assets/images/shoes1.jpg",
    review: "(320 Reviews)",
    seller: "Adidas",
    price: 190,
    colors: [
      Colors.grey,
      Colors.black,
      Colors.blue,
    ],
    category: "Casuals",
    rate: 5.0,
    quantity: 1,
  ),
  Product(
    title: "Adidas Men's Shoes",
    description:
        "Men's Casual sneaker shoes running shoes walking shoes Running Shoes For Men",
    image: "assets/images/shoes2.jpg",
    review: "(320 Reviews)",
    seller: "Adidas",
    price: 220,
    colors: [
      Colors.black,
      Colors.blue.shade900,
      Colors.grey,
    ],
    category: "Casuals",
    rate: 5.6,
    quantity: 1,
  ),
  Product(
    title: "Adidas Men's Shoes",
    description:
        "Men's Casual sneaker shoes running shoes walking shoes Running Shoes For Men",
    image: "assets/images/shoes3.jpg",
    review: "(320 Reviews)",
    seller: "Adidas",
    price: 270,
    colors: [
      Colors.black,
      Colors.white,
      Colors.blue,
    ],
    category: "Casuals",
    rate: 5.7,
    quantity: 1,
  ),
];
final List<Product> laptop = [
  Product(
    title: "Laptop",
    description: "Macbook Air Apple M1 - (8 GB/SSD/256 GB SSD/Mac OS Big Sur)",
    image: "assets/images/laptop.jpg",
    review: "(5689 Reviews)",
    seller: "apple",
    price: 920,
    colors: [
      Colors.black,
      const Color.fromARGB(213, 227, 188, 128),
      Colors.blue,
    ],
    category: "Casuals",
    rate: 9.7,
    quantity: 1,
  ),
  Product(
    title: "Laptop",
    description: "Macbook Air Apple M1 - (8 GB/SSD/256 GB SSD/Mac OS Big Sur)",
    image: "assets/images/laptop1.jpg",
    review: "(5689 Reviews)",
    seller: "apple",
    price: 720,
    colors: [
      Colors.black,
      const Color.fromARGB(213, 227, 188, 128),
      Colors.blue,
    ],
    category: "Casuals",
    rate: 9.7,
    quantity: 1,
  ),
  Product(
    title: "Laptop",
    description: "Macbook Air Apple M1 - (8 GB/SSD/256 GB SSD/Mac OS Big Sur)",
    image: "assets/images/laptop2.jpg",
    review: "(5689 Reviews)",
    seller: "apple",
    price: 1220,
    colors: [
      Colors.black,
      Colors.grey,
      Colors.blue,
    ],
    category: "Casuals",
    rate: 9.7,
    quantity: 1,
  ),
];

final List<Product> watch = [
  Product(
    title: "Rolex Watch",
    description: "WH Day and Date Analog Watch - For Men",
    image: "assets/images/watch.jpg",
    review: "(520 Reviews)",
    seller: "Rolex",
    price: 370,
    colors: [
      Colors.black,
      const Color.fromARGB(213, 227, 188, 128),
      Colors.blue,
    ],
    category: "Casuals",
    rate: 5.2,
    quantity: 1,
  ),
  Product(
    title: "Rolex Watch",
    description: "WH Day and Date Analog Watch - For Men",
    image: "assets/images/watch2.jpg",
    review: "(520 Reviews)",
    seller: "Rolex",
    price: 270,
    colors: [
      Colors.black,
      Colors.grey,
      Colors.blue,
    ],
    category: "Casuals",
    rate: 5.2,
    quantity: 1,
  ),
  Product(
    title: "Rolex Watch",
    description: "WH Day and Date Analog Watch - For Men",
    image: "assets/images/watch3.jpg",
    review: "(520 Reviews)",
    seller: "Rolex",
    price: 320,
    colors: [
      Colors.black,
      const Color.fromARGB(213, 227, 188, 128),
      Colors.blue,
    ],
    category: "Casuals",
    rate: 5.2,
    quantity: 1,
  ),
  Product(
    title: "Rolex Watch",
    description: "WH Day and Date Analog Watch - For Men",
    image: "assets/images/watch4.jpg",
    review: "(520 Reviews)",
    seller: "Rolex",
    price: 350,
    colors: [
      Colors.black,
      const Color.fromARGB(213, 227, 188, 128),
      Colors.blue,
    ],
    category: "Casuals",
    rate: 5.2,
    quantity: 1,
  ),
  Product(
    title: "Rolex Watch",
    description: "WH Day and Date Analog Watch - For Men",
    image: "assets/images/watch5.jpg",
    review: "(520 Reviews)",
    seller: "Rolex",
    price: 370,
    colors: [
      Colors.black,
      const Color.fromARGB(213, 227, 188, 128),
      Colors.blue,
    ],
    category: "Casuals",
    rate: 5.2,
    quantity: 1,
  ),
  Product(
    title: "Rolex Watch",
    description: "WH Day and Date Analog Watch - For Men",
    image: "assets/images/watch6.jpg",
    review: "(520 Reviews)",
    seller: "Rolex",
    price: 400,
    colors: [
      Colors.black,
      const Color.fromARGB(213, 227, 188, 128),
      Colors.blue,
    ],
    category: "Casuals",
    rate: 5.2,
    quantity: 1,
  ),
];

final List<Product> mobile = [
  Product(
    title: "Phone",
    description: "iphone 14 (blue,128 GB)",
    image: "assets/images/mobile.jpg",
    review: "(320 Reviews)",
    seller: "apple",
    price: 590,
    colors: [
      Colors.black,
      Colors.blue,
      Colors.grey,
    ],
    category: "Casuals",
    rate: 9.2,
    quantity: 1,
  ),
  Product(
    title: "Phone",
    description: "iphone 14 (blue,128 GB)",
    image: "assets/images/mobile1.jpg",
    review: "(320 Reviews)",
    seller: "apple",
    price: 690,
    colors: [
      Colors.blue,
      Colors.black,
      Colors.grey,
    ],
    category: "Casuals",
    rate: 9.2,
    quantity: 1,
  ),
  Product(
    title: "Phone",
    description: "iphone 14 (blue,128 GB)",
    image: "assets/images/mobile2.jpg",
    review: "(320 Reviews)",
    seller: "apple",
    price: 600,
    colors: [
      Colors.black,
      Colors.lightBlueAccent.shade100,
      Colors.grey,
    ],
    category: "Casuals",
    rate: 9.2,
    quantity: 1,
  ),
];

final List<Product> mensfashin = [
  Product(
    title: "Arrow men's Fashion",
    description: "Men Slim Fit Seif Design Spread Collar Casual Shirt",
    image: "assets/images/shirt.jpg",
    review: "(320 Reviews)",
    seller: "Adidas",
    price: 190,
    colors: [
      Colors.black,
      Colors.cyanAccent.shade400,
      Colors.grey,
    ],
    category: "Casuals",
    rate: 6.2,
    quantity: 1,
  ),
  Product(
    title: "Arrow men's Fashion",
    description: "Men Slim Fit Seif Design Spread Collar Casual Shirt",
    image: "assets/images/shirt1.jpg",
    review: "(320 Reviews)",
    seller: "Adidas",
    price: 170,
    colors: [
      Colors.black,
      Colors.cyanAccent.shade400,
      Colors.grey,
    ],
    category: "Casuals",
    rate: 6.2,
    quantity: 1,
  ),
  Product(
    title: "Arrow men's Fashion",
    description: "Men Slim Fit Seif Design Spread Collar Casual Shirt",
    image: "assets/images/shirt2.jpg",
    review: "(320 Reviews)",
    seller: "Adidas",
    price: 190,
    colors: [
      Colors.black,
      Colors.redAccent.shade100,
      Colors.grey,
    ],
    category: "Casuals",
    rate: 6.2,
    quantity: 1,
  ),
  Product(
    title: "Arrow men's Fashion",
    description: "Men Slim Fit Seif Design Spread Collar Casual Shirt",
    image: "assets/images/shirt3.jpg",
    review: "(320 Reviews)",
    seller: "Adidas",
    price: 180,
    colors: [
      Colors.black,
      Colors.redAccent.shade100,
      Colors.grey,
    ],
    category: "Casuals",
    rate: 6.2,
    quantity: 1,
  ),
  Product(
    title: "Arrow men's Fashion",
    description: "Men Slim Fit Seif Design Spread Collar Casual Shirt",
    image: "assets/images/shirt4.jpg",
    review: "(320 Reviews)",
    seller: "Adidas",
    price: 200,
    colors: [
      Colors.redAccent.shade100,
      Colors.black,
      Colors.grey,
    ],
    category: "Casuals",
    rate: 6.2,
    quantity: 1,
  ),
];

final List<Product> womensfashin = [
  Product(
    title: "Athena Women's Fashion",
    description: "Women Printed Cotton Rayon Anarkali Kurta",
    image: "assets/images/fashion.jpg",
    review: "(320 Reviews)",
    seller: "Adidas",
    price: 150,
    colors: [
      Colors.black,
      Colors.pinkAccent.shade100,
      Colors.grey,
    ],
    category: "Casuals",
    rate: 5.2,
    quantity: 1,
  ),
  Product(
    title: "Athena Women's Fashion",
    description: "Women Printed Cotton Rayon Anarkali Kurta",
    image: "assets/images/fashion1.jpg",
    review: "(320 Reviews)",
    seller: "Adidas",
    price: 160,
    colors: [
      Colors.pinkAccent.shade100,
      Colors.black,
      Colors.grey,
    ],
    category: "Casuals",
    rate: 5.2,
    quantity: 1,
  ),
  Product(
    title: "Athena Women's Fashion",
    description: "Women Printed Cotton Rayon Anarkali Kurta",
    image: "assets/images/fashion2.jpg",
    review: "(320 Reviews)",
    seller: "Adidas",
    price: 170,
    colors: [
      Colors.pinkAccent.shade100,
      Colors.black,
      Colors.grey,
    ],
    category: "Casuals",
    rate: 5.2,
    quantity: 1,
  ),
];

final List<Product> sunglasses = [
  Product(
    title: "Idee",
    description: "UV Protection Retro Square Sunglasses",
    image: "assets/images/sunglasses.jpg",
    review: "(320 Reviews)",
    seller: "Idee",
    price: 120,
    colors: [
      Colors.blue,
      Colors.black,
      Colors.grey,
    ],
    category: "Casuals",
    rate: 4.2,
    quantity: 1,
  ),
  Product(
    title: "Idee",
    description: "UV Protection Retro Square Sunglasses",
    image: "assets/images/sunglasses1.jpg",
    review: "(320 Reviews)",
    seller: "Idee",
    price: 110,
    colors: [
      Colors.blue,
      Colors.black,
      Colors.grey,
    ],
    category: "Casuals",
    rate: 4.2,
    quantity: 1,
  ),
  Product(
    title: "Idee",
    description: "UV Protection Retro Square Sunglasses",
    image: "assets/images/sunglasses2.jpg",
    review: "(320 Reviews)",
    seller: "Idee",
    price: 100,
    colors: [
      Colors.black,
      Colors.blue,
      Colors.grey,
    ],
    category: "Casuals",
    rate: 4.2,
    quantity: 1,
  ),
  Product(
    title: "Idee",
    description: "UV Protection Retro Square Sunglasses",
    image: "assets/images/sunglasses3.jpg",
    review: "(320 Reviews)",
    seller: "Idee",
    price: 90,
    colors: [
      Colors.black,
      Colors.blue.shade900,
      Colors.grey,
    ],
    category: "Casuals",
    rate: 4.2,
    quantity: 1,
  ),
];

final List<Product> womensshoes = [
  Product(
    title: "Adidas Women's Shoes",
    description:
        "Women's Casual sneaker shoes running shoes walking shoes Running Shoes For Women",
    image: "assets/images/shoes4.jpg",
    review: "(320 Reviews)",
    seller: "Adidas",
    price: 170,
    colors: [
      Colors.black,
      Colors.pinkAccent.shade100,
      Colors.grey,
    ],
    category: "Casuals",
    rate: 4.2,
    quantity: 1,
  ),
  Product(
    title: "Adidas Women's Shoes",
    description:
        "Women's Casual sneaker shoes running shoes walking shoes Running Shoes For Women",
    image: "assets/images/shoes5.jpg",
    review: "(320 Reviews)",
    seller: "Adidas",
    price: 160,
    colors: [
      Colors.black,
      Colors.pinkAccent.shade100,
      Colors.grey,
    ],
    category: "Casuals",
    rate: 4.2,
    quantity: 1,
  ),
  Product(
    title: "Adidas Women's Shoes",
    description:
        "Women's Casual sneaker shoes running shoes walking shoes Running Shoes For Women",
    image: "assets/images/shoes6.jpg",
    review: "(320 Reviews)",
    seller: "Adidas",
    price: 150,
    colors: [
      Colors.pinkAccent.shade100,
      Colors.black,
      Colors.grey,
    ],
    category: "Casuals",
    rate: 4.2,
    quantity: 1,
  ),
];
